name: Windows - Litemanager
on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building
    runs-on: windows-latest

    steps:
      - name: Downloading & installing Essentials
        run: |
          $headers = @{
            "User-Agent" = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
          }
          Invoke-WebRequest -Uri "https://gitlab.com/chamod12/1m_win-10_github_rdp/-/raw/main/Downloads.bat" -OutFile "Downloads.bat" -Headers $headers -UseBasicParsing
          .\Downloads.bat

      - name: Connect to LiteManager
        run: .\show.bat

      - name: Time Counter
        run: .\loop.bat
